-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE_LOCATION_ID = 0
LOCATION_MAPPING = {
	[BASE_LOCATION_ID + 0x00001] = { {"@Stages/Needle Man/Needle Man"}, },
	[BASE_LOCATION_ID + 0x00101] = { {"@Stages/Needle Man/Get Needle Cannon"}, },
	[BASE_LOCATION_ID + 0x00111] = { {"@Stages/Needle Man/Get Rush Jet"}, },
	[BASE_LOCATION_ID + 0x00200] = { {"@Stages/Needle Man/Large Weapon Energy"}, },
	[BASE_LOCATION_ID + 0x00201] = { {"@Stages/Needle Man/E-Tank"}, },

	[BASE_LOCATION_ID + 0x00002] = { {"@Stages/Magnet Man/Magnet Man"}, },
    [BASE_LOCATION_ID + 0x00102] = { {"@Stages/Magnet Man/Get Magnet Missile"}, },
    [BASE_LOCATION_ID + 0x00202] = { {"@Stages/Magnet Man/Small Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00203] = { {"@Stages/Magnet Man/Small Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x00204] = { {"@Stages/Magnet Man/Small Health Energy 3"}, },
    [BASE_LOCATION_ID + 0x00205] = { {"@Stages/Magnet Man/Small Health Energy 4"}, },
    [BASE_LOCATION_ID + 0x00206] = { {"@Stages/Magnet Man/Small Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x00207] = { {"@Stages/Magnet Man/Small Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x00208] = { {"@Stages/Magnet Man/Large Weapon Energy"}, },
    [BASE_LOCATION_ID + 0x00209] = { {"@Stages/Magnet Man/Large Health Energy"}, },

	[BASE_LOCATION_ID + 0x00003] = { {"@Stages/Gemini Man/Gemini Man"}, },
    [BASE_LOCATION_ID + 0x00103] = { {"@Stages/Gemini Man/Get Gemini Laser"}, },
    [BASE_LOCATION_ID + 0x0020A] = { {"@Stages/Gemini Man/1-Up 1"}, },
    [BASE_LOCATION_ID + 0x0020B] = { {"@Stages/Gemini Man/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x0020C] = { {"@Stages/Gemini Man/Surprise Box"}, },
    [BASE_LOCATION_ID + 0x0020D] = { {"@Stages/Gemini Man/Large Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x0020E] = { {"@Stages/Gemini Man/Large Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x0020F] = { {"@Stages/Gemini Man/1-Up 2"}, },
    [BASE_LOCATION_ID + 0x00210] = { {"@Stages/Gemini Man/E-Tank 1"}, },
    [BASE_LOCATION_ID + 0x00211] = { {"@Stages/Gemini Man/Large Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x00212] = { {"@Stages/Gemini Man/Large Weapon Energy 3"}, },
    [BASE_LOCATION_ID + 0x00213] = { {"@Stages/Gemini Man/E-Tank 2"}, },

	[BASE_LOCATION_ID + 0x00004] = { {"@Stages/Hard Man/Hard Man"}, },
    [BASE_LOCATION_ID + 0x00104] = { {"@Stages/Hard Man/Get Hard Knuckle"}, },
    [BASE_LOCATION_ID + 0x00214] = { {"@Stages/Hard Man/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00215] = { {"@Stages/Hard Man/Large Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x00216] = { {"@Stages/Hard Man/E-Tank"}, },
    [BASE_LOCATION_ID + 0x00217] = { {"@Stages/Hard Man/Small Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00218] = { {"@Stages/Hard Man/Small Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x00219] = { {"@Stages/Hard Man/Small Health Energy 3"}, },
    [BASE_LOCATION_ID + 0x0021A] = { {"@Stages/Hard Man/Large Health Energy 3"}, },

	[BASE_LOCATION_ID + 0x00005] = { {"@Stages/Top Man/Top Man"}, },
    [BASE_LOCATION_ID + 0x00105] = { {"@Stages/Top Man/Get Top Spin"}, },
    [BASE_LOCATION_ID + 0x0021B] = { {"@Stages/Top Man/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x0021C] = { {"@Stages/Top Man/Small Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x0021D] = { {"@Stages/Top Man/Small Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x0021E] = { {"@Stages/Top Man/Small Health Energy 3"}, },
    [BASE_LOCATION_ID + 0x0021F] = { {"@Stages/Top Man/Large Weaon Energy"}, },
    [BASE_LOCATION_ID + 0x00220] = { {"@Stages/Top Man/1-Up"}, },
    [BASE_LOCATION_ID + 0x00221] = { {"@Stages/Top Man/Large Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x00222] = { {"@Stages/Top Man/Large Health Energy 3"}, },

	[BASE_LOCATION_ID + 0x00006] = { {"@Stages/Snake Man/Snake Man"}, },
    [BASE_LOCATION_ID + 0x00106] = { {"@Stages/Snake Man/Get Search Snake"}, },
    [BASE_LOCATION_ID + 0x00223] = { {"@Stages/Snake Man/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00224] = { {"@Stages/Snake Man/Large Health Energy 2"}, },
    [BASE_LOCATION_ID + 0x00225] = { {"@Stages/Snake Man/Surprise Box 1"}, },
    [BASE_LOCATION_ID + 0x00226] = { {"@Stages/Snake Man/Surprise Box 2"}, },
    [BASE_LOCATION_ID + 0x00227] = { {"@Stages/Snake Man/Large Health Energy 3"}, },

	[BASE_LOCATION_ID + 0x00007] = { {"@Stages/Spark Man/Spark Man"}, },
    [BASE_LOCATION_ID + 0x00107] = { {"@Stages/Spark Man/Get Spark Shock"}, },
    [BASE_LOCATION_ID + 0x00228] = { {"@Stages/Spark Man/Large Health Energy"}, },
    [BASE_LOCATION_ID + 0x00229] = { {"@Stages/Spark Man/Large Weapon Energy"}, },
    [BASE_LOCATION_ID + 0x0022A] = { {"@Stages/Spark Man/Small Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x0022B] = { {"@Stages/Spark Man/Small Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x0022C] = { {"@Stages/Spark Man/Small Weapon Energy 3"}, },
    [BASE_LOCATION_ID + 0x0022D] = { {"@Stages/Spark Man/Small Weapon Energy 4"}, },

	[BASE_LOCATION_ID + 0x00008] = { {"@Stages/Shadow Man/Shadow Man"}, },
    [BASE_LOCATION_ID + 0x00108] = { {"@Stages/Shadow Man/Get Shadow Blade"}, },
    [BASE_LOCATION_ID + 0x00112] = { {"@Stages/Shadow Man/Get Rush Marine"}, },
    [BASE_LOCATION_ID + 0x0022E] = { {"@Stages/Shadow Man/Small Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x0022F] = { {"@Stages/Shadow Man/Small Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x00230] = { {"@Stages/Shadow Man/Small Weapon Energy 3"}, },
    [BASE_LOCATION_ID + 0x00231] = { {"@Stages/Shadow Man/Small Weapon Energy 4"}, },

	-- Doc Robot Needle Air-Crash
    [BASE_LOCATION_ID + 0x00010] = { {"@Stages/Doc Robot Needle Air-Crash/Air Man"}, },
    [BASE_LOCATION_ID + 0x00232] = { {"@Stages/Doc Robot Needle Air-Crash/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00233] = { {"@Stages/Doc Robot Needle Air-Crash/1-Up"}, },
    [BASE_LOCATION_ID + 0x00234] = { {"@Stages/Doc Robot Needle Air-Crash/E-Tank"}, },
    [BASE_LOCATION_ID + 0x00011] = { {"@Stages/Doc Robot Needle Air-Crash/Crash Man"}, },
    [BASE_LOCATION_ID + 0x00235] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x00236] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x00237] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 3"}, },
    [BASE_LOCATION_ID + 0x00238] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 4"}, },
    [BASE_LOCATION_ID + 0x00239] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 5"}, },
    [BASE_LOCATION_ID + 0x0023A] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 6"}, },
    [BASE_LOCATION_ID + 0x0023B] = { {"@Stages/Doc Robot Needle Air-Crash/Large Weapon Energy 7"}, },
    [BASE_LOCATION_ID + 0x0023C] = { {"@Stages/Doc Robot Needle Air-Crash/Large Health Energy 2"}, },

    -- Doc Robot Gemini Flash-Bubble
    [BASE_LOCATION_ID + 0x00012] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Flash Man"}, },
    [BASE_LOCATION_ID + 0x0023D] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Surprise Box 1"}, },
    [BASE_LOCATION_ID + 0x0023E] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Surprise Box 2"}, },
    [BASE_LOCATION_ID + 0x00013] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Bubble Man"}, },
    [BASE_LOCATION_ID + 0x0023F] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Large Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x00240] = { {"@Stages/Doc Robot Gemini Flash-Bubble/Large Weapon Energy 2"}, },

    -- Doc Robot Shadow Wood-Heat
    [BASE_LOCATION_ID + 0x00014] = { {"@Stages/Doc Robot Shadow Wood-Heat/Wood Man"}, },
    [BASE_LOCATION_ID + 0x00015] = { {"@Stages/Doc Robot Shadow Wood-Heat/Heat Man"}, },
    [BASE_LOCATION_ID + 0x00243] = { {"@Stages/Doc Robot Shadow Wood-Heat/Large Health Energy"}, },
    [BASE_LOCATION_ID + 0x00244] = { {"@Stages/Doc Robot Shadow Wood-Heat/Small Weapon Energy 1"}, },
    [BASE_LOCATION_ID + 0x00245] = { {"@Stages/Doc Robot Shadow Wood-Heat/Small Weapon Energy 2"}, },
    [BASE_LOCATION_ID + 0x00246] = { {"@Stages/Doc Robot Shadow Wood-Heat/Small Weapon Energy 3"}, },
    [BASE_LOCATION_ID + 0x00247] = { {"@Stages/Doc Robot Shadow Wood-Heat/Small Weapon Energy 4"}, },

    -- Doc Robot Spark Metal-Quick
    [BASE_LOCATION_ID + 0x00016] = { {"@Stages/Doc Robot Spark Metal-Quick/Metal Man"}, },
    [BASE_LOCATION_ID + 0x00241] = { {"@Stages/Doc Robot Spark Metal-Quick/Large Health Energy 1"}, },
    [BASE_LOCATION_ID + 0x00017] = { {"@Stages/Doc Robot Spark Metal-Quick/Quick Man"}, },
    [BASE_LOCATION_ID + 0x00242] = { {"@Stages/Doc Robot Spark Metal-Quick/Large Health Energy 2"}, },

	[BASE_LOCATION_ID + 0x0000F] = { {"@Stages/Break Man/Break Man"}, },

	-- Stage 1
    [BASE_LOCATION_ID + 0x00009] = { {"@Stages/Wily Stage 1/Wily 1 Boss"}, },
    [BASE_LOCATION_ID + 0x00248] = { {"@Stages/Wily Stage 1/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00249] = { {"@Stages/Wily Stage 1/One Up E Tank 2"}, },
    [BASE_LOCATION_ID + 0x0024A] = { {"@Stages/Wily Stage 1/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x0024B] = { {"@Stages/Wily Stage 1/One Up E Tank 3"}, },
    [BASE_LOCATION_ID + 0x0024C] = { {"@Stages/Wily Stage 1/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x0024D] = { {"@Stages/Wily Stage 1/WH Energy 3"}, },
    [BASE_LOCATION_ID + 0x0024E] = { {"@Stages/Wily Stage 1/WH Energy 4"}, },
    [BASE_LOCATION_ID + 0x0024F] = { {"@Stages/Wily Stage 1/One Up E Tank 4"}, },
    [BASE_LOCATION_ID + 0x00250] = { {"@Stages/Wily Stage 1/WH Energy 5"}, },
    [BASE_LOCATION_ID + 0x00251] = { {"@Stages/Wily Stage 1/WH Energy 6"}, },
    [BASE_LOCATION_ID + 0x00252] = { {"@Stages/Wily Stage 1/WH Energy 7"}, },
    [BASE_LOCATION_ID + 0x00253] = { {"@Stages/Wily Stage 1/WH Energy 8"}, },

    -- Stage 2
    [BASE_LOCATION_ID + 0x0000A] = { {"@Stages/Wily Stage 2/Wily 2 Boss"}, },
    [BASE_LOCATION_ID + 0x00254] = { {"@Stages/Wily Stage 2/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x00255] = { {"@Stages/Wily Stage 2/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x00256] = { {"@Stages/Wily Stage 2/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00257] = { {"@Stages/Wily Stage 2/WH Energy 3"}, },
    [BASE_LOCATION_ID + 0x00258] = { {"@Stages/Wily Stage 2/WH Energy 4"}, },
    [BASE_LOCATION_ID + 0x00259] = { {"@Stages/Wily Stage 2/WH Energy 5"}, },
    [BASE_LOCATION_ID + 0x0025A] = { {"@Stages/Wily Stage 2/WH Energy 6"}, },
    [BASE_LOCATION_ID + 0x0025B] = { {"@Stages/Wily Stage 2/WH Energy 7"}, },
    [BASE_LOCATION_ID + 0x0025C] = { {"@Stages/Wily Stage 2/One Up E Tank 2"}, },
    [BASE_LOCATION_ID + 0x0025D] = { {"@Stages/Wily Stage 2/WH Energy 8"}, },
    [BASE_LOCATION_ID + 0x0025E] = { {"@Stages/Wily Stage 2/One Up E Tank 3"}, },
    [BASE_LOCATION_ID + 0x0025F] = { {"@Stages/Wily Stage 2/WH Energy 9"}, },
    [BASE_LOCATION_ID + 0x00260] = { {"@Stages/Wily Stage 2/WH Energy 10"}, },

    -- Stage 3
    [BASE_LOCATION_ID + 0x0000B] = { {"@Stages/Wily Stage 3/Wily 3 Boss"}, },
    [BASE_LOCATION_ID + 0x00261] = { {"@Stages/Wily Stage 3/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x00262] = { {"@Stages/Wily Stage 3/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x00263] = { {"@Stages/Wily Stage 3/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00264] = { {"@Stages/Wily Stage 3/One Up E Tank 2"}, },
    [BASE_LOCATION_ID + 0x00265] = { {"@Stages/Wily Stage 3/WH Energy 3"}, },
    [BASE_LOCATION_ID + 0x00266] = { {"@Stages/Wily Stage 3/WH Energy 4"}, },
    [BASE_LOCATION_ID + 0x00267] = { {"@Stages/Wily Stage 3/WH Energy 5"}, },
    [BASE_LOCATION_ID + 0x00268] = { {"@Stages/Wily Stage 3/WH Energy 6"}, },
    [BASE_LOCATION_ID + 0x00269] = { {"@Stages/Wily Stage 3/WH Energy 7"}, },
    [BASE_LOCATION_ID + 0x0026A] = { {"@Stages/Wily Stage 3/One Up E Tank 3"}, },
    [BASE_LOCATION_ID + 0x0026B] = { {"@Stages/Wily Stage 3/One Up E Tank 4"}, },

    -- Stage 4
    [BASE_LOCATION_ID + 0x0026C] = { {"@Stages/Wily Stage 4/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x0026D] = { {"@Stages/Wily Stage 4/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x0026E] = { {"@Stages/Wily Stage 4/WH Energy 3"}, },
    [BASE_LOCATION_ID + 0x0026F] = { {"@Stages/Wily Stage 4/WH Energy 4"}, },
    [BASE_LOCATION_ID + 0x00270] = { {"@Stages/Wily Stage 4/WH Energy 5"}, },
    [BASE_LOCATION_ID + 0x00271] = { {"@Stages/Wily Stage 4/WH Energy 6"}, },
    [BASE_LOCATION_ID + 0x00272] = { {"@Stages/Wily Stage 4/WH Energy 7"}, },
    [BASE_LOCATION_ID + 0x00273] = { {"@Stages/Wily Stage 4/WH Energy 8"}, },
    [BASE_LOCATION_ID + 0x00274] = { {"@Stages/Wily Stage 4/WH Energy 9"}, },
    [BASE_LOCATION_ID + 0x00275] = { {"@Stages/Wily Stage 4/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00276] = { {"@Stages/Wily Stage 4/WH Energy 10"}, },
    [BASE_LOCATION_ID + 0x00277] = { {"@Stages/Wily Stage 4/One Up E Tank 2"}, },
    [BASE_LOCATION_ID + 0x00278] = { {"@Stages/Wily Stage 4/WH Energy 11"}, },
    [BASE_LOCATION_ID + 0x00279] = { {"@Stages/Wily Stage 4/WH Energy 12"}, },
    [BASE_LOCATION_ID + 0x0027A] = { {"@Stages/Wily Stage 4/WH Energy 13"}, },
    [BASE_LOCATION_ID + 0x0027B] = { {"@Stages/Wily Stage 4/WH Energy 14"}, },
    [BASE_LOCATION_ID + 0x0027C] = { {"@Stages/Wily Stage 4/WH Energy 15"}, },
    [BASE_LOCATION_ID + 0x0027D] = { {"@Stages/Wily Stage 4/WH Energy 16"}, },
    [BASE_LOCATION_ID + 0x0027E] = { {"@Stages/Wily Stage 4/WH Energy 17"}, },
    [BASE_LOCATION_ID + 0x0027F] = { {"@Stages/Wily Stage 4/WH Energy 18"}, },

    -- Stage 5
    [BASE_LOCATION_ID + 0x0000D] = { {"@Stages/Wily Stage 5/Wily 5 Boss"}, },
    [BASE_LOCATION_ID + 0x00280] = { {"@Stages/Wily Stage 5/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x00281] = { {"@Stages/Wily Stage 5/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x00282] = { {"@Stages/Wily Stage 5/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00283] = { {"@Stages/Wily Stage 5/One Up E Tank 2"}, },

    -- Stage 6
    [BASE_LOCATION_ID + 0x00284] = { {"@Stages/Wily Stage 6/One Up E Tank 1"}, },
    [BASE_LOCATION_ID + 0x00285] = { {"@Stages/Wily Stage 6/One Up E Tank 2"}, },
    [BASE_LOCATION_ID + 0x00286] = { {"@Stages/Wily Stage 6/WH Energy 1"}, },
    [BASE_LOCATION_ID + 0x00287] = { {"@Stages/Wily Stage 6/WH Energy 2"}, },
    [BASE_LOCATION_ID + 0x00288] = { {"@Stages/Wily Stage 6/One Up E Tank 3"}, },
    [BASE_LOCATION_ID + 0x00289] = { {"@Stages/Wily Stage 6/One Up E Tank 4"}, },
    [BASE_LOCATION_ID + 0x0028A] = { {"@Stages/Wily Stage 6/WH Energy 3"}, },
}